name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd public_html/purple/repo
            git pull
            npm run build
            cd out
            # Remove old build artifacts from destination
            rm -rf ../../404 ../../404.html ../../images ../../_next ../../*.html ../../*.txt ../../*.json ../../*.ico
            # Move new build files to destination
            mv * ../../

